# .streamlit/secrets.toml (Existing content for Firestore + new sections)

[firestore]
# ... (your existing Firestore credentials) ...

[openai]
api_key = "sk-YOUR_OPENAI_API_KEY_HERE"

[google]
api_key = "AIzaSy_YOUR_GOOGLE_API_KEY_HERE" # For Gemini, etc.

[ollama]
# If using a local Ollama server, you might not need an API key,
# but could specify server URL or model.
# api_url = "http://localhost:11434"
# model = "llama3"

[football_data]
api_key = "YOUR_FOOTBALL_DATA_API_KEY_HERE"

[nba_data]
api_key = "YOUR_NBA_DATA_API_KEY_HERE"

# Add other LLM or sports API keys as needed
