# .streamlit/secrets.toml (Existing content for Firestore + new sections)

[firestore]
# Example:
# type = "service_account"
# project_id = "your-project-id"
# private_key_id = "your-private-key-id"
# private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
# client_email = "your-service-account@your-project-id.iam.gserviceaccount.com"
# client_id = "your-client-id"
# auth_uri = "https://accounts.google.com/o/oauth2/auth"
# token_uri = "https://oauth2.googleapis.com/token"
# auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
# client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project-id.iam.gserviceaccount.com"
# universe_domain = "googleapis.com"


[openai]
api_key = "sk-YOUR_OPENAI_API_KEY_HERE" # Replace with your actual OpenAI API Key

[google]
api_key = "AIzaSy_YOUR_GOOGLE_API_KEY_HERE" # Replace with your actual Google API Key (for Gemini, etc.)

[ollama]
# If using a local Ollama server, you might not need an API key,
# but could specify server URL or model.
# api_url = "http://localhost:11434"
# model = "llama3"

# --- Sports API Keys ---
[thesportsdb]
api_key = "YOUR_THESPORTSDB_API_KEY_HERE" # Get from https://www.thesportsdb.com/api.php

[api_football]
api_key = "YOUR_API_FOOTBALL_API_KEY_HERE" # Get from https://www.api-football.com/

[serpapi]
api_key = "YOUR_SERPAPI_API_KEY_HERE" # Get from https://serpapi.com/

# --- Media API Keys ---
[themoviedb]
api_key = "YOUR_THEMOVIEDB_API_KEY_HERE" # Get from https://www.themoviedb.org/documentation/api

[omdbapi]
api_key = "YOUR_OMDBAPI_API_KEY_HERE" # Get from http://www.omdbapi.com/apikey.aspx

[google_custom_search]
api_key = "YOUR_GOOGLE_CUSTOM_SEARCH_API_KEY_HERE" # From Google Cloud Console, Custom Search API

# --- Email SMTP Credentials (if not using environment variables) ---
# For security, these are best handled by Streamlit secrets or environment variables
# [email]
# smtp_user = "your_actual_email@example.com"
# smtp_password = "your_email_app_password"

# Example of a top-level secret for email credentials (as used in the test)
email_smtp_user = "your_actual_email@example.com"
email_smtp_password = "your_email_app_password"

# .streamlit/secrets.toml

[alphavantage]
api_key = "YOUR_ALPHAVANTAGE_API_KEY_HERE" # Get from https://www.alphavantage.co/support/#api-key

[financial_news]
api_key = "YOUR_FINANCIAL_NEWS_API_KEY_HERE" # Replace with your actual key if you implement this

# .streamlit/secrets.toml (Add these lines)

[coingecko]
api_key = "YOUR_COINGECKO_API_KEY_HERE" # Only if you use a paid plan, otherwise leave empty or remove.

[exchangerate_api]
api_key = "YOUR_EXCHANGERATE_API_KEY_HERE" # Get from https://www.exchangerate-api.com/


# .streamlit/secrets.toml (Add these lines)

[health_api]
api_key = "YOUR_HEALTH_API_KEY_HERE" # Replace with your actual key for a medical API

[who_api]
api_key = "YOUR_WHO_API_KEY_HERE" # Replace with your actual key for a WHO/global health API

[google_maps_api]
api_key = "YOUR_GOOGLE_MAPS_API_KEY_HERE" # Replace with your actual Google Maps API key (e.g., for Places API)

# .streamlit/secrets.toml (Add these lines)

[openweathermap]
api_key = "YOUR_OPENWEATHERMAP_API_KEY_HERE" # Replace with your actual OpenWeatherMap API key

[weatherapi]
api_key = "YOUR_WEATHERAPI_API_KEY_HERE" # Replace with your actual WeatherAPI.com API key
