# .streamlit/secrets.toml (Existing content for Firestore + new sections)

[firestore]
# ... (your existing Firestore credentials) ...

[openai]
api_key = "sk-YOUR_OPENAI_API_KEY_HERE"

[google]
api_key = "AIzaSy_YOUR_GOOGLE_API_KEY_HERE" # For Gemini, etc.

[ollama]
# If using a local Ollama server, you might not need an API key,
# but could specify server URL or model.
# api_url = "http://localhost:11434"
# model = "llama3"

# --- Sports API Keys ---
[thesportsdb]
api_key = "YOUR_THESPORTSDB_API_KEY_HERE" # Get from https://www.thesportsdb.com/api.php

[api_football]
api_key = "YOUR_API_FOOTBALL_API_KEY_HERE" # Get from https://www.api-football.com/

[serpapi]
api_key = "YOUR_SERPAPI_API_KEY_HERE" # Get from https://serpapi.com/

# --- Media API Keys ---
[themoviedb]
api_key = "YOUR_THEMOVIEDB_API_KEY_HERE" # Get from https://www.themoviedb.org/documentation/api

[omdbapi]
api_key = "YOUR_OMDBAPI_API_KEY_HERE" # Get from http://www.omdbapi.com/apikey.aspx

[google_custom_search]
api_key = "YOUR_GOOGLE_CUSTOM_SEARCH_API_KEY_HERE" # From Google Cloud Console, Custom Search API
cx = "YOUR_CUSTOM_SEARCH_ENGINE_ID_HERE" # From Google Custom Search Engine settings

# Add other LLM or specific API keys as needed
